### PR TITLE
feat: register functionality

### PR DESCRIPTION
**Pull request by sojida**
**What does this Merge request do?**

This PR implements the register functionality

**Description of Task to be completed?**

- user can register

**How should this be manually tested?**

- navigate to /register
- fill out form
- click 'Register'

**Any background context you want to provide?**

xxx

**What are the relevant Trello cards/stories?**

xxx

**Screenshots (if appropriate)**

Screenshot from 2020-07-06 15-20-04

Screenshot from 2020-07-06 15-20-13

**Questions:**

xxx

### CODE REVIEW

**Comment by sojida** [comment]
@9trocode I just pushed an update to make register the homepage...it works. Kindly review

**Comment by 9trocode** [comment]
> @9trocode I just pushed an update to make register the homepage...it works. Kindly review

Okay nice it works now well done sir

**Comment by 9trocode** [comment]
My password is being displayed back to me if it does not meet requirements should it be that way?? @sojida cc @victory

Screenshot (7)

**Comment by sojida** [comment]
@9trocode Password display issue fixed:

Screenshot from 2020-07-08 20-13-56

**Comment by 9trocode** [comment]
> @9trocode Password display issue fixed:
> 
> Screenshot from 2020-07-08 20-13-56

well done @sojida

**Pull request merged**
