### PR TITLE
Setup & Router Setup

### PR DESCRIPTION
**Pull request by adenekan41**
**What does this Merge request do?**

- Project Setup
- Router Setup

**Description of Task to be completed?**

- React Setup

**How should this be manually tested?**
localhost:3000

**Any background context you want to provide?**

- None

**Screenshots (if appropriate)**
- None

**Questions:**

- None

### CODE REVIEW

**Comment by 9trocode** [comment]
nice work @adenekan41,  @otseobande @sojida @vic3king let's look into this

**Comment by adenekan41** [comment]
The app ?. just yarn and start

**Comment by 9trocode** [comment]
> The app ?. just yarn and start cc: @9trocode

Still not working though @adenekan41 seems like a dependency issue

**Comment by 9trocode** [comment]
@adenekan41 can you commit and push your yarn.lock I think it's a dependency tree issue

**Pull request merged**
